### ISSUE TITLE
Problem check_on_centos() and check_on_macos()

### ISSUE THREAD

**Issue by biplab44** [r-hub/rhub#533] opened 2022-07-31 08:40 UTC
When I tried running check_on_centos() and check_on_macos() today, these gave the error Unknown R-hub platform:

```
> rhub::check_on_centos()
Error in match_platform(platform) : 
  Unknown R-hub platform, see rhub::platforms() for a list
```

same for `rhub::check_on_macos()` also whereas all other platforms works well.
I assume this is a temporary issue. I couldn't find a related issue.

**Comment by gaborcsardi** [comment] 2022-07-31 09:33
Duplicate of #450.

**Closed by gaborcsardi** 2022-07-31 09:33 UTC
