### ISSUE TITLE
Mail says PREPERROR but build log says SUCCESS

### ISSUE THREAD

**Issue by RafaelEduardoDiaz** [r-hub/rhub#448] opened 2021-02-22 01:36 UTC
Hello, I would like to request help with this problem, similar to how it happened to another user. The logs say successful status, but the email says error, I can't understand what happens.
Any help I appreciate.

Full log here: [https://builder.r-hub.io/status/Bayeshmmcts_0.0.1.tar.gz-0e1e179e390a451e8465d9bd96ff79c7](url)

![image](https://user-images.githubusercontent.com/32598165/108646399-aef8a280-7483-11eb-8148-4b9c3c4b63e2.png)

![image](https://user-images.githubusercontent.com/32598165/108646460-f1ba7a80-7483-11eb-8749-f936e668292f.png)

**Comment by dmenne** [comment] 2021-03-09 10:18
I have exactly the same problem, my package with rstan dmenne/gastempt even passes CRAN incoming, but fails on winbuilder. I assume it is because we both have a second NOTE because of the use of GNU extensions.

This is a long standing issue, its always a waste of time to wade through pages of output just to note the "success" at the end. Please fix it, r-hubbers! I never have managed to get a green output despite having 4 packages on CRAN.

**Comment by gaborcsardi** [comment] 2021-03-09 10:33
You need to show some examples.

**Comment by dmenne** [comment] 2021-03-09 11:04
See the example of the original poster, or

https://artifacts.r-hub.io/gastempt_0.5.4.tar.gz-6e76bbc708114f5984e5fcf1db6c9bbd/gastempt.Rcheck/tests_i386/

![a](https://user-images.githubusercontent.com/506275/110460753-e5166300-80ce-11eb-92ed-441a7b46c302.png)

**Comment by gaborcsardi** [comment] 2021-03-09 11:38
The original poster referred to a different build for PREPERROR than the linked one. The linked one is a `NOTE`, so green.

**Comment by dcnorris** [comment] 2021-04-03 15:16
In case additional examples are useful ...
https://builder.r-hub.io/status/original/precautionary_0.2-2.tar.gz-45f46cdb9ab546d899c536ed1b3d16b7
<img width="570" alt="image" src="https://user-images.githubusercontent.com/8365445/113482723-f05e7380-946d-11eb-8cd7-519454943d30.png">

**Comment by samFarrellDay** [comment] 2021-05-13 15:00
This is happening on both packages I maintain - here is an example from each:
https://builder.r-hub.io/status/ParBayesianOptimization_1.2.5.tar.gz-bc6d47d807204fd1afe730114bc8d51b
https://builder.r-hub.io/status/miceRanger_1.4.0.tar.gz-af30439a9ff145aba7973788f0b2a783

R CMD says OK, status is Success, email says PREPERROR like the picture above.

**Comment by njtierney** [comment] 2021-05-26 01:32
I also have the same issue:

https://builder.r-hub.io/status/brolgar_0.1.1.tar.gz-51b120fcc8b5464cbfd955e4c1111857

**Comment by laresbernardo** [comment] 2021-06-04 16:00
Same issue here:
linux-x86_64-centos-epel: https://builder.r-hub.io/status/original/lares_5.0.1.tar.gz-53c9d9d388ca459e832e0068e0634e0b

**Comment by ycphs** [comment] 2021-06-15 10:44
Same here

[windows](https://builder.r-hub.io/status/original/openxlsx_4.2.4.tar.gz-e14490b1bbe14166bc1d80c48bf2dcbb)

**Comment by bbolker** [comment] 2021-09-16 16:39
As far as I can tell this hasn't been resolved yet ... ? e.g.

![Screenshot from 2021-09-16 12-38-48](https://user-images.githubusercontent.com/78918/133651572-d82887ee-a2a3-488f-8cbc-c37ba8a11a75.png)
![Screenshot from 2021-09-16 12-39-05](https://user-images.githubusercontent.com/78918/133651595-df2729a7-1b25-4eb0-8542-76b7c8dc3c30.png)

**Comment by gaborcsardi** [comment] 2021-09-16 16:44
Indeed has not.

**Comment by DRJP** [comment] 2021-11-16 14:44
Hi.

I also appear to be hitting up against the same bug - always when rhub checks on Ubuntu (I've no problems when rhub checks on Fedora or Windows).  The build log can be found [here](https://builder.r-hub.io/status/original/nimbleAPT_1.0.4.tar.gz-dc7160cc9b1c431ea53754f0481c64e8) and the artefacts can be found [here](https://artifacts.r-hub.io/nimbleAPT_1.0.4.tar.gz-dc7160cc9b1c431ea53754f0481c64e8/). 

Best regards
David
![preperror](https://user-images.githubusercontent.com/18430130/141999286-32cc1de3-755e-447d-b32c-215f634b5947.png)

**Comment by jonas-hag** [comment] 2022-01-11 12:34
I have the same issue that I get an e-mail with PREPERROR but the status shows success (and RMD check run). See the logs: [HTML](https://builder.r-hub.io/status/longmixr_1.0.0.tar.gz-0c8a446b4024426d8eca7058a01c2c51), [text](https://builder.r-hub.io/status/original/longmixr_1.0.0.tar.gz-0c8a446b4024426d8eca7058a01c2c51) and [artifacts](https://artifacts.r-hub.io/longmixr_1.0.0.tar.gz-0c8a446b4024426d8eca7058a01c2c51). On Windows, I don't have any problems.

I've found that in my logs there are some errors mentioned:

> #> Failed with error: ‘there is no package called ‘shiny’’

this seems to be due to a strange DESCRIPTION file by `htmlwidgets` but I assume it doesn't matter as on windows it's ok
and
> 16781 docker rm longmixr_1.0.0.tar.gz-0c8a446b4024426d8eca7058a01c2c51-3
> 16782#> Error: No such container: longmixr_1.0.0.tar.gz-0c8a446b4024426d8eca7058a01c2c51-3

maybe this is the reason?

Thanks for this great service! Please let me know if you need more info or if I can otherwise help to solve this issue.

**Comment by bbolker** [comment] 2022-03-14 00:12
Still having this problem with glmmTMB (33 minute build) ...

**Comment by dmenne** [comment] 2022-03-14 07:38
I gave up using r-hub...

**Comment by ntamas** [comment] 2022-03-29 01:30
I'd like to add `igraph` to the list of packages where the mail says `PREPERROR` but the logs indicate success; see [here](https://builder.r-hub.io/status/igraph_1.2.11.9169.tar.gz-5ebab37fc75e4ddb8b7a44f39b44f050).

Most likely caused by these lines at the end:

```
#> docker rm igraph_1.2.11.9169.tar.gz-5ebab37fc75e4ddb8b7a44f39b44f050-1

#> Error: No such container: igraph_1.2.11.9169.tar.gz-5ebab37fc75e4ddb8b7a44f39b44f050-1

true

docker rm igraph_1.2.11.9169.tar.gz-5ebab37fc75e4ddb8b7a44f39b44f050-2

#> igraph_1.2.11.9169.tar.gz-5ebab37fc75e4ddb8b7a44f39b44f050-2

docker rm igraph_1.2.11.9169.tar.gz-5ebab37fc75e4ddb8b7a44f39b44f050-3

#> Error: No such container: igraph_1.2.11.9169.tar.gz-5ebab37fc75e4ddb8b7a44f39b44f050-3
```

Two out of the three `docker rm` calls return `Error: No such container:`. Happens only with `linux-x86_64-rocker-gcc-san`.

**Comment by gaborcsardi** [comment] 2022-03-29 10:06
No, the reason is https://github.com/r-hub/rhub/issues/448#issuecomment-793776145, i.e. the log is too long and our internal scheduler truncates it, so our app thinks that it stopped there.

No need to add more "me too" comments, thank you! :) Also no need to ask if this is still a problem, if this issue is open then it is a problem. :) Here is a somewhat longer explanation why: https://github.com/golang/go/wiki/NoPlusOne/

**Comment by gaborcsardi** [comment] 2024-05-09 12:52
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.

**Closed by gaborcsardi** 2024-05-09 12:52 UTC
Labels: bug
