### ISSUE TITLE
Specific versions on https://builder.r-hub.io/advanced

### ISSUE THREAD

**Issue by LiNk-NY** [r-hub/rhub#140] opened 2018-05-30 20:00 UTC
Hi Gábor, @gaborcsardi 

It would be good to be able to see what versions of R "release" and "devel" refer to on
this page https://builder.r-hub.io/advanced.

These tags are relative and can change after the release of a new version of R. 
It would be good to see the version numbers for these R versions in addition to their
usual tags (_especially_ when a new version has been recently released). 

Thanks for your attention. 

Regards,
Marcel

**Comment by maelle** [comment] 2019-02-26 10:33
Thanks! Duplicate of https://github.com/r-hub/feedback/issues/7

**Closed by maelle** 2019-02-26 10:33 UTC
