### ISSUE TITLE
Local use of rhub/fedora-clang-devel fails with BioConductor

### ISSUE THREAD

**Issue by eddelbuettel** [r-hub/rhub#391] opened 2020-07-01 12:47 UTC
Started as `local_check_linux("mylocalpackage_1.2.3.tar.gz", image="rhub/fedora-clang-devel") `

Starts out well enough updating F31 but then

```sh
>>>>>==================== Starting Docker container
8ab7d6d4e14eeb6f0d8bb5c3de74e223ecea43dd89228310b72fb260f034b187
> source('https://bioconductor.org/biocLite.R')
Error: With R version 3.5 or greater, install Bioconductor packages using BiocManager; see https://bioconductor.org/install
Execution halted
Error in run(bash, c(file.path(wd, "rhub-linux.sh"), args), echo = TRUE,  : 
  System command 'bash' failed, exit status: 1, stdout & stderr were printed
Type .Last.error.trace to see where the error occured
R> 
```

**Comment by eddelbuettel** [comment] 2020-07-01 12:51
Worse, it fails even when I have _zero_ BioC Suggests.  That is ... pretty bad.

**Comment by eddelbuettel** [comment] 2020-07-01 12:57
And joy oh joy it is the same for `rhub/debian-clang-devel` so I just wasted two containers downloads.  Well it looked like a nice idea at the time.

**Comment by gaborcsardi** [comment] 2020-07-01 13:07
Duplicate of https://github.com/r-hub/rhub/issues/390

**Comment by eddelbuettel** [comment] 2020-07-01 13:17
Sorry. I made two searches for BioConductor but did not find anything.  Odd I missed that one.  I tried, and failed.  :-/

So when will you update the (clearly identified as broken) CRAN version?

**Comment by gaborcsardi** [comment] 2024-05-09 12:47
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.

**Closed by gaborcsardi** 2024-05-09 12:47 UTC
