### ISSUE TITLE
openmp is not enabled on OS/X

### ISSUE THREAD

**Issue by jpritikin** [r-hub/rhub#121] opened 2018-02-23 14:59 UTC
Doesn't clang support openmp now? Doesn't CRAN enable openmp for OS/X binaries?

**Comment by gaborcsardi** [comment] 2018-02-23 16:29
The standard macOS / xcode toolchain is used on the builders. There are arguments for both this and CRANs special clang, and unfortunately you cannot install / run multiple R versions on the same machine, so not easy to add new ones.

**Comment by jpritikin** [comment] 2018-02-23 16:32
Oh, I'm happy as long as r-hub is the same as CRAN.

**Comment by jpritikin** [comment] 2018-02-23 16:39
I mean, this isn't just a theoretical concern. CRAN has failed to build OS/X binaries for the OpenMx package for months now. I have no way to diagnose the cause because CRAN uses some funky toolchain. That's why I was so excited about r-hub. I figured r-hub would be a way to finally determine why OpenMx failed to build correctly on CRAN.

**Comment by jpritikin** [comment] 2018-02-23 21:48
What are the arguments a for standard macOS / xcode toolchain in favor of matching CRAN exactly?

**Comment by gaborcsardi** [comment] 2018-02-23 21:51
Yeah, I guess the issue is whether we want to replicate CRAN exactly, or replicate what the users have. I doubt that many users bother with installing the special clang version, since everything works just fine without it, and you need a special Makevars to use the CRAN compiler.

As I said, there are arguments for both, and as I see it now, I think we can actually support both, we just need to provide a way to switch between them.

**Comment by gaborcsardi** [comment] 2018-02-24 10:05
Will be fixed via https://github.com/r-hub/devops-issues/issues/8 We'll just copy a `~/.R/Makevars` file to the builder. We can also provide a nicer API in the rhub R package over this.

**Comment by jpritikin** [comment] 2018-03-23 14:44
Any progress here? We are eager to debug OS/X builds as soon as rhub can build exactly like CRAN.

**Comment by bflammers** [comment] 2019-04-05 07:46
Also looking forward to this! This would indeed help a lot with debugging CRAN check errors.

**Comment by gaborcsardi** [comment] 2022-08-31 12:20
This has been "solved" by CRAN abandoning openmp on macOS.

**Closed by gaborcsardi** 2022-08-31 12:20 UTC
Labels: big win, user request
