### ISSUE TITLE
preperror

### ISSUE THREAD

**Issue by ycphs** [r-hub/rhub#321] opened 2019-11-27 20:26 UTC
preperror for Fedora Linux, R-devel, clang, gfortran

https://builder.r-hub.io/status/original/openxlsx_4.1.3.9007.tar.gz-421794defdef45458ff301393c669f1f

completed for Windows Server 2008 R2 SP1, R-devel, 32/64 bit

**Comment by phargarten2** [comment] 2019-12-12 17:02
Duplicate of #318.

**Comment by gaborcsardi** [comment] 2024-05-09 12:43
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.

**Closed by gaborcsardi** 2024-05-09 12:43 UTC
