### ISSUE TITLE
`framed.sty` missing on Fedora Linux, R-devel, clang, gfortran

### ISSUE THREAD

**Issue by phargarten2** [r-hub/rhub#397] opened 2020-07-20 23:46 UTC
Thanks for making Rhub! It makes it so much easier to make sure my package is ready for CRAN. 

The Fedora Linux platform is apparently missing the `framed.sty` file.

Platform: | Fedora Linux, R-devel, clang, gfortran
Submitted: | 7 hours 13 minutes 47.6 seconds ago
Build time: | 3 hours 21 minutes 36.3 seconds

```
* checking re-building of vignette outputs ... WARNING
Error(s) in re-building vignettes:
--- re-building ‘README.Rmd’ using rmarkdown
! LaTeX Error: File `framed.sty' not found.

! Emergency stop.
<read *> 

! kpathsea: Running mktexfmt pdflatex.fmt
! mktexfmt: mktexfmt is using the following fmtutil.cnf files (in precedence order):
! mktexfmt:   /usr/share/texlive/texmf-dist/web2c/fmtutil.cnf
! mktexfmt: mktexfmt is using the following fmtutil.cnf file for writing changes:
! mktexfmt:   /home/docker/.texlive2019/texmf-config/web2c/fmtutil.cnf
! mktexfmt [INFO]: writing formats under /home/docker/.texlive2019/texmf-var/web2c
! mktexfmt [INFO]: --- remaking pdflatex with pdftex
! mktexfmt: running `pdftex -ini   -jobname=pdflatex -progname=pdflatex -translate-file=cp227.tcx *pdflatex.ini' ...
! This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019) (INITEX)
```

**Comment by MatthieuStigler** [comment] 2021-07-27 04:46
I confirm the problem, tried on the same Fedora Linux, R-devel, clang, gfortran, and having same message *File `framed.sty' not found.*

**Comment by pboesu** [comment] 2022-04-20 10:39
I'm getting the same error using `rhub::check_for_cran` on the `fedora-clang-devel` platform. 
Full check log here: https://builder.r-hub.io/status/deBInfer_0.4.3.tar.gz-f519c6fb17d64425ba50fff8afacf175

**Comment by gaborcsardi** [comment] 2022-08-31 11:54
Duplicate of #523, which is more generic, so I'll close this one.

**Closed by gaborcsardi** 2022-08-31 11:54 UTC
