### ISSUE TITLE
Windows build odd note, not created?

### ISSUE THREAD

**Issue by guyas** [r-hub/rhub#504] opened 2022-01-25 14:34 UTC
Tried to push an update today using devtools::check_rhub(), got this weird message:
`N  checking for detritus in the temp directory
   Found the following files/directories:
     'lastMiKTeXException'`

No such file or directory was anywhere to be found. Prior to pushing I have built the manual, the package, checked it, checked `as-cran`, the whole shebang - it has all passed perfectly. The [CRAN webpage](https://cran.rstudio.com/web/packages/LogRegEquiv/) seems to indicate the pack was not updated, although [the build was successful](https://builder.r-hub.io/status/LogRegEquiv_0.1.3.tar.gz-c0e36595e2a049c18bb7b18462935292). 

I have tried restarting R and RStudio, but the problem persisted.

Any ideas?

```
√  checking for non-standard things in the check directory
N  checking for detritus in the temp directory
   Found the following files/directories:
     'lastMiKTeXException'
   
-  Done with R CMD check
-  Cleaning up files and user
    

-- LogRegEquiv 0.1.3: NOTE

  Build ID:   LogRegEquiv_0.1.3.tar.gz-c0e36595e2a049c18bb7b18462935292
  Platform:   Windows Server 2022, R-devel, 64 bit
  Submitted:  4m 33.1s ago
  Build time: 3m 40s

> checking for detritus in the temp directory ... NOTE
  Found the following files/directories:
    'lastMiKTeXException'

0 errors √ | 0 warnings √ | 1 note x

-- LogRegEquiv 0.1.3: CREATED

  Build ID:   LogRegEquiv_0.1.3.tar.gz-9806cf95810a4df882ee1fa87f3e9bef
  Platform:   Ubuntu Linux 20.04.1 LTS, R-release, GCC
  Submitted:  4m 33.2s ago


-- LogRegEquiv 0.1.3: CREATED

  Build ID:   LogRegEquiv_0.1.3.tar.gz-89180b8492024c0488f843870a4c01c7
  Platform:   Fedora Linux, R-devel, clang, gfortran
  Submitted:  4m 33.2s ago

```

**Comment by gaborcsardi** [comment] 2022-01-25 14:39
Duplicate of #503?

**Closed by gaborcsardi** 2022-01-25 14:39 UTC

**Comment by guyas** [comment] 2022-01-25 14:41
It seems so, sorry.
