### ISSUE TITLE
rgdal fails to install on ubuntu

### ISSUE THREAD

**Issue by rmendels** [r-hub/rhub#276] opened 2019-05-22 17:58 UTC
From build ID rerddapXtracto_0.3.5.tar.gz-9b5f8bd83cc244f6aa9a7e370366e1ea

#> * installing *source* package ‘rgdal’ ...
2885#> ** package ‘rgdal’ successfully unpacked and MD5 sums checked
2886#> ** using staged installation
2887#> configure: R_HOME: /usr/lib/R
2888#> configure: CC: gcc -std=gnu99
2889#> configure: CXX: g++ -std=gnu++11
2890#> configure: C++11 support available
2891#> configure: rgdal: 1.4-3
2892#> checking for /usr/bin/svnversion... yes
2893#> configure: svn revision: 828
2894#> checking for gdal-config... /usr/bin/gdal-config
2895#> checking gdal-config usability... yes
2896#> configure: GDAL: 1.11.3
2897#> checking GDAL version >= 1.11.4... no
2898#> configure: error: upgrade GDAL to 1.11.4 or later
2899#> ERROR: configuration failed for package ‘rgdal’

**Comment by maelle** [comment] 2019-05-23 04:23
Thanks @rmendels ! Sorry to only realize now this is probably a duplicate of https://github.com/r-hub/rhub/issues/258

**Comment by mikemahoney218** [comment] 2020-02-09 02:37
Hi all! Still having this problem with the Ubuntu image in particular -- I get the same output as listed above for Ubuntu 16.04 LTS only

**Comment by gaborcsardi** [comment] 2024-05-09 12:41
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.

**Closed by gaborcsardi** 2024-05-09 12:41 UTC
Labels: sysreqs
