### ISSUE TITLE
Issue with Windows Server 2008 R2 SP1, R-devel, 32/64 bit

### ISSUE THREAD

**Issue by FranciscoPalomares** [r-hub/rhub#352] opened 2020-03-10 12:19 UTC
![image](https://user-images.githubusercontent.com/39648210/76311637-ac805580-62d1-11ea-9e48-11df8680c43c.png)

Artifact link: https://artifacts.r-hub.io/SSLR_0.9.0.tar.gz-97802d5741af4a6c9d88878d5e2ea937/SSLR.Rcheck/00install.out

** byte-compile and prepare package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'ggplot2'
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted

**Comment by gaborcsardi** [comment] 2020-03-10 12:58
This is a bug in the remotes package (and maybe base R) which we use for package installation. It happens because some packages are installed from source, and from binaries, and the installation order is incorrect.

It will go away once the ggplot2 package will have binaries available on CRAN.

**Comment by gaborcsardi** [comment] 2020-03-11 01:54
I have updated the remotes version R-hub uses, please try again.

**Comment by Hong-Revo** [comment] 2020-03-11 14:48
Possibly related: I've just run into a failure to find the remotes package on Windows.

https://builder.r-hub.io/status/AzureContainers_1.2.1.tar.gz-35b15c3fe82c4798b351dc866d346169
https://artifacts.r-hub.io/AzureContainers_1.2.1.tar.gz-35b15c3fe82c4798b351dc866d346169/AzureContainers.Rcheck/00check.log

![image](https://user-images.githubusercontent.com/11328890/76429493-3c71ec80-6403-11ea-9da6-bc99b5e3baa3.png)

**Comment by jdblischak** [comment] 2020-03-11 14:52
@Hong-Revo I can confirm that I am currently getting the same error:

```
> source('install-github.R')$value('r-lib/remotes@r-hub')
Error: Failed to install 'remotes' from GitHub:
JSON: EXPECTED value GOT "
Execution halted
```

https://builder.r-hub.io/status/workflowr_1.6.1.tar.gz-c5c9b6c944b34660abf192ae6323776b#L128

**Comment by gaborcsardi** [comment] 2020-03-12 01:31
This should be fixed now.

**Closed by gaborcsardi** 2020-03-12 01:31 UTC

**Comment by jdblischak** [comment] 2020-03-14 00:57
Confirmed that `check_on_windows()` works again. @gaborcsardi Thanks for maintaining such a great resource!
