### ISSUE TITLE
Missing Latex File `framed.sty` on Fedora Linux, R-devel, clang, gfortran

### ISSUE THREAD

**Issue by phargarten2** [r-hub/rhub#454] opened 2021-04-02 03:12 UTC
Thank you for this package to allow me to run my package, `miWQS`, in many different environments. I found a missing LaTex file on this platform:
`framed.sty`

```{r}
Build ID:miWQS_0.4.4.tar.gz-41b3a3666357424a876ce0915306deb4Platform:Fedora Linux, R-devel, clang, gfortranSubmitted:21 minutes 0.4 seconds agoBuild time:20 minutes 59.4 seconds | Build ID: | miWQS_0.4.4.tar.gz-41b3a3666357424a876ce0915306deb4 | Platform: | Fedora Linux, R-devel, clang, gfortran | Submitted: | 21 minutes 0.4 seconds ago | Build time: | 20 minutes 59.4 seconds
-- | -- | -- | -- | -- | -- | -- | -- | --
Build ID: | miWQS_0.4.4.tar.gz-41b3a3666357424a876ce0915306deb4
Platform: | Fedora Linux, R-devel, clang, gfortran
Submitted: | 21 minutes 0.4 seconds ago
Build time: | 20 minutes 59.4 seconds
WARNINGS:* checking re-building of vignette outputs ... WARNING Error(s) in re-building vignettes: --- re-building ‘README.Rmd’ using rmarkdown Warning in has_crop_tools() :    Tool(s) not installed or not in PATH: pdfcrop -> As a result, figure cropping will be disabled. ! LaTeX Error: File `framed.sty' not found.
```

**Comment by MLopez-Ibanez** [comment] 2022-10-23 12:53
Duplicate of issue #541

**Comment by gaborcsardi** [comment] 2024-05-09 12:56
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.

**Closed by gaborcsardi** 2024-05-09 12:56 UTC
