### ISSUE TITLE
Mention BLAS implementation used on servers, offer various implementations.

### ISSUE THREAD

**Issue by ghost** [r-hub/rhub#275] opened 2019-05-21 09:54 UTC
The configurations of r-hub's server farm do not seem to mention the BLAS implemtations used. CRAN seems to have started to use different BLAS implementions or at least additional checks so I believe it is worthwhile to a) mention what r-hub offers and b) even offer various BLAS implementations on r-hub.

But maybe I did not find the right spot in the documentation?

**Comment by gaborcsardi** [comment] 2019-05-21 10:33
R-hub uses the platform and R default, everywhere.

We could have an extra one, maybe. Do you have particular suggestions? What does CRAN use for their extra checks?

**Comment by helix123** [comment] 2019-05-21 11:13
r-devel-linux-x86_64-debian-gcc  started to use OpenBLAS (we ere notified as an error was caused by numerical precision), but it is not documented as far as I can see. And I don't know they plan to continue to use OpenBLAS for this platform.

There seem to be additional checks on CRAN (at least for some packages, see e.g. `data.table`) with various BLASes: https://cran.rstudio.com/web/checks/check_issue_kinds.html

**Comment by maelle** [comment] 2019-05-22 09:45
I randomly found the [R Journal article mentioning the change](https://journal.r-project.org/archive/2018-1/cran.pdf) "The  package  check  pages  now  also  show  issues  found  by  checks  with  alternativeBLAS/LAPACK implementations (ATLAS, MKL and OpenBLAS), provided by Brian D. Rip-ley (seehttps://www.stats.ox.ac.uk/pub/bdr/Rblas/README.txtfor more information)."

**Comment by config-i1** [comment] 2020-08-03 14:22
Some of the packages have now received strikes from CRAN, because they don't pass some of the checks on ATLAS / MKL. So, it would help a lot to package maintainers if there were additional checks on rhub to include those different versions of BLAS.

**Comment by jepusto** [comment] 2020-08-28 11:42
Seconded. It would be tremendously helpful (and would alleviate work for the CRAN maintainers) to be able to test against the MKL configuration used for CRAN checks. Here is the description of the builds:
https://www.stats.ox.ac.uk/pub/bdr/Rblas/README.txt

**Comment by gaborcsardi** [comment] 2020-08-28 11:56
I am afraid that we cannot legally publish a Docker container with MKL. But I am not entirely sure.

**Comment by Bisaloo** [comment] 2021-03-21 09:50
We had a floating point precision issue that only shows up on CRAN checks with ATLAS. We tried to fix it by adjusting the tolerance in `expect_equal()` but we have no way to verify this is sufficient before pushing it to CRAN.

A rhub platform would be amazing :+1:!

**Comment by statnmap** [comment] 2021-07-21 12:29
In the same idea, I found today the list of additional issues with this list of complementary tests:
![image](https://user-images.githubusercontent.com/21193866/126487380-6b67a8ef-b316-4361-ae8f-44e924cfb6e5.png)
If you click on additional issues on this page: https://cran.r-project.org/web/checks/check_results_gitdown.html, you will find the list above: https://cran.r-project.org/web/checks/check_issue_kinds.html (until I submit a new version)

In case it is useful, details lead to README pages from some of these directories: https://www.stats.ox.ac.uk/pub/bdr/

@Bisaloo I also got some floating point precision problems. I decided to transform values into text for unit tests (dates in my case).

**Comment by gaborcsardi** [comment] 2024-05-09 12:53
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.

**Closed by gaborcsardi** 2024-05-09 12:53 UTC
