### ISSUE TITLE
PREPERRORs on solaris, install-github.me failure

### ISSUE THREAD

**Issue by obrl-soil** [r-hub/rhub#492] opened 2021-11-11 03:11 UTC
Running `rhub::check_for_cran(platforms = c('solaris-x86-patched-ods', 'solaris-x86-patched'))`, I get:

  * https://builder.r-hub.io/status/h3jsr_1.2.3.tar.gz-8ab1169906ba4005b958237cb475944a
  * https://builder.r-hub.io/status/h3jsr_1.2.3.tar.gz-6fd0b33f8b334cd6937bcf4824e5be2d

Both seem to be having a problem with install-github.me being deprecated and `remotes` subsequently failing to install. #444 suggests this is not a problem; is that still true? There are also some messages about lock files that differ between the two checks.

The turnaround time was too fast for the package to have actually been checked.

Messaging from each build:
```
Installing package dependencies
  46#> Fatal server error:
  47#> Could not create server lock file: /tmp/.X47-lock
  48#> 'getOption("repos")' replaces Bioconductor standard repositories, see
  49#> '?repositories' for details
  50#> replacement repositories:
  51#> CRAN: https://cloud.r-project.org
  52#> > source("https://install-github.me/r-lib/remotes@r-hub")
  53#> The install-github.me service is deprecated, please stop using it.
  54#> Error: Failed to install 'remotes' from GitHub:
  55#> cannot open URL 'https://api.github.com/repos/r-lib/remotes/contents/DESCRIPTION?ref=r-hub'
  56#> Execution halted
  57#> Saving artifacts
  58#> cp: cannot access /export/home/XhW7gOn/h3jsr.Rcheck
  59#> Cleaning up user and home directory
  60#> SSH: Connecting from host [unknown]
  61#> SSH: Connecting with configuration [files] ...
  62#> SSH: Disconnecting configuration [files] ...
  63#> SSH: Transferred 1 file(s)
  64#> Build step 'Send files or execute commands over SSH' changed build result to SUCCESS
  65#> Pinging https://builder.r-hub.io/build/SUCCESS/h3jsr_1.2.3.tar.gz-8ab1169906ba4005b958237cb475944a/2021-11-11T02:51:37Z
  66#> {"status":"ok"}
  67#> Finished: SUCCESS
```
```
Installing package dependencies
  47#> Fatal server error:
  48#> Server is already active for display 57
  49#> If this server is no longer running, remove /tmp/.X57-lock
  50#> and start again.
  51#> 'getOption("repos")' replaces Bioconductor standard repositories, see
  52#> '?repositories' for details
  53#> replacement repositories:
  54#> CRAN: https://cloud.r-project.org
  55#> > source("https://install-github.me/r-lib/remotes@r-hub")
  56#> The install-github.me service is deprecated, please stop using it.
  57#> Error: Failed to install 'remotes' from GitHub:
  58#> cannot open URL 'https://api.github.com/repos/r-lib/remotes/contens/DESCRIPTION?ref=r-hub'
  59#> Execution halted
  60#> Saving artifacts
  61#> cp: cannot access /export/home/XCHjiHi/h3jsr.Rcheck
  62#> Cleaning up user and home directory
  63#> SSH: Connecting from host [unknown]
  64#> SSH: Connecting with configuration [files] ...
  65#> SSH: Disconnecting configuration [files] ...
  66#> SSH: Transferred 1 file(s)
  67#> Build step 'Send files or execute commands over SSH' changed build result to SUCCESS
  68#> Pinging https://builder.r-hub.io/build/SUCCESS/h3jsr_1.2.3.tar.gz-6fd0b33f8b334cd6937bcf4824e5be2d/2021-11-11T02:51:37Z
  69#> {"status":"ok"}
  70#> Finished: SUCCESS
```

**Comment by gaborcsardi** [comment] 2021-11-11 08:15
This is a duplicate of #193.

**Closed by gaborcsardi** 2021-11-11 08:15 UTC
