### ISSUE TITLE
rhub says ggplot2 not available

### ISSUE THREAD

**Issue by rolfTurner** [r-hub/rhub#354] opened 2020-03-11 00:49 UTC
A short while ago I submitted an updated version of a package to rhub to get a Windoze binary built.  I did this by invoking the check() function from the rhub package.

I got an error that I don't understand: 

E  checking package dependencies
   Package required but not available: 'ggplot2'

But I used rhub to build a Windoze binary of the previous version of the package without any such error, and the dependency of the package upon ggplot2 has not changed.

What should I do?

**Comment by gaborcsardi** [comment] 2020-03-11 00:54
Duplicate of #352.

**Comment by rolfTurner** [comment] 2020-03-11 01:09
I'm still confused.  The CRAN page says that ggplot2 version 3.3.0 was released
on 2020-03-05, six days ago.  My (successful)  build of the previous version of the package took place on 2020-03-06.  What has changed?  I note that the Windoze binaries of ggplot2 on CRAN are:

r-release: ggplot2_3.2.1.zip, r-oldrel: ggplot2_3.3.0.zip

so version 3.3.0 is indeed not available for r-release.  But would not that have applied equally on 2020-03-06???

**Comment by gaborcsardi** [comment] 2020-03-11 01:17
It is this bug: https://github.com/r-lib/remotes/issues/296

**Comment by rolfTurner** [comment] 2020-03-11 01:27
Is there anything i can do (to get a Windoze binary of my package built?  Do I just have to wait until the updated binary of ggplot2 appears on CRAN?  Is there any way to tell how long that will be?

**Comment by gaborcsardi** [comment] 2020-03-11 01:54
I have updated the remotes version R-hub uses, please try again.

**Closed** 2020-03-11 01:54 UTC

**Comment by rolfTurner** [comment] 2020-03-11 22:52
I have tried again, twice.  Both times I got a whole *load* of packages that were "required but not available":

'lme4', 'brms', 'glmmTMB', 'GLMMadaptive', 'Rcpp', 'rmutil',
     'ggplot2', 'ggforce', 'gdata'

So things have got worse!!! :-)
