### ISSUE TITLE
Missing Latex .sty file for Fedora

### ISSUE THREAD

**Issue by SteffenMoritz** [r-hub/rhub#137] opened 2018-05-23 12:30 UTC
Build ID: | imputeTS_2.7.tar.gz-1015249378884f92a527dbe93ed6f394
-- | --
Platform: | Fedora Linux, R-devel, clang, gfortran
Submitted: | 10 minutes 34.5 seconds ago
Build time: | 10 minutes 28.4 seconds

* checking re-building of vignette outputs ... WARNING
Error in re-building vignettes:
  ...
Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
  Running 'texi2dvi' on 'imputeTS-Time-Series-Missing-Value-Imputation-in-R.tex' failed.
LaTeX errors:
! LaTeX Error: File `microtype.sty' not found.

Since the `microtype.sty' file does not miss for all other os and there is also no error on CRAN my guess would be, that on your Fedora system no full Latex distribution is installed.

**Comment by gaborcsardi** [comment] 2022-08-31 12:19
Duplicate of #523

**Closed by gaborcsardi** 2022-08-31 12:19 UTC
Labels: sysreqs, latex
